from dataclasses import dataclass

from src.core.events.base.base_event import BaseEvent


@dataclass(frozen=True)
class FibonacciNumber(BaseEvent):
    """
    Emitted when a Fibonacci number is generated by the FibonacciNumberProducer.
    """

    value: int
