from dataclasses import dataclass
from src.core.contracts.event import Event

@dataclass(frozen=True)
class FibonacciNumber(Event):
    """
    Emitted when a Fibonacci number is generated by the FibonacciNumberProducer.
    """
    
    value: int