from dataclasses import dataclass

from src.core.events.base.base_event import BaseEvent


@dataclass(frozen=True)
class RandomNumber(BaseEvent):
    """
    Emiited when a random number is generated by the RandomNumberProducer.
    """

    value: float
