from dataclasses import dataclass
from src.core.contracts.event import Event


@dataclass(frozen=True)
class RandomNumber(Event):
    """
    Emiited when a random number is generated by the RandomNumberProducer.
    """
    
    value: float